# Generated by Django 6.0.4 on 2026-04-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cor'),
        ),
    ]
