# Generated by Django 6.0.4 on 2026-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='codigo',
            field=models.CharField(default='#FFFFFF', help_text='Ex: #FF0000', max_length=7),
        ),
    ]
