# Generated by Django 6.0.4 on 2026-04-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
