"""
Django settings for configuracao project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from pathlib import Path

import dj_database_url # Instale com: pip install dj-database-url

import logging

LANGUAGE_CODE = 'pt-br'  # Define o idioma como Português do Brasil
TIME_ZONE = 'America/Sao_Paulo' # Ajusta o fuso horário

USE_I18N = True   # Ativa a tradução internacional
USE_L10N = False   # Ativa a localização (formatos de números e datas)
USE_TZ = True     # Ativa o fuso horário

USE_THOUSAND_SEPARATOR = True # Separador de milhar
THOUSAND_SEPARATOR = '.'    # Separador de milhar
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-v5$6*s$_&p2^!l!%9k0k)cb-#&^1j)xxh=mc-y8z6mnj=o611!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['bazar-maria.onrender.com', 'localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configuracao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- CONFIGURAÇÃO DE ARMAZENAMENTO (CLOUDINARY) ---

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'dqhdejpsr'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '598351497964753'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', '2Q33pKZG3ZkvFvRDj9zfoooZxfg'),
    'PREFIX': 'bazar_maria',
    'SECURE': True,
    'LONG_URL_SIGNATURE': False,
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

# COMPATIBILIDADE: Isso resolve o erro 'AttributeError: STATICFILES_STORAGE'
DEFAULT_FILE_STORAGE = STORAGES["default"]["BACKEND"]
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Isso diz ao Django onde procurar seus arquivos CSS/JS personalizados
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Isso ajuda o WhiteNoise a encontrar os arquivos mais facilmente em alguns servidores
WHITENOISE_USE_FINDERS = True

MEDIA_URL = '/media/'

# --- LOGGING PARA DIAGNÓSTICO ---

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'cloudinary_storage': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

FORMAT_MODULE_PATH = [
    'BazarMaria.formats',
]

# Prints de segurança (ajustados para não dar erro)
print("DEBUG: Configurações de Storage carregadas com sucesso.")

